import type { PageServerLoad } from './$types';
import fs from 'fs';
import path from 'path';
import { parsePrismaSchema } from './parse-prisma-schema';

// import { spawn, exec } from 'child_process';
// const paths = { root: '/home/mili/Extensions/event-handler' };
// function execShell(cmd: string): Promise<string> {
// 	return new Promise((resolve, reject) => {
// 		exec(cmd, { cwd: paths.root }, (err, stdout, stderr) => {
// 			if (err) {
// 				reject(new Error(`Command failed: ${stderr}`));
// 				return;
// 			}
// 			resolve(stdout);
// 		});
// 	});
// }
// const sudoName_ = (await execShell('whoami')).trim();
// console.log(sudoName_);

// function runCommandStream(
// 	command: string,
// 	args: string[],
// 	options: {
// 		cwd?: string;
// 		onStdout?: (data: string) => void;
// 		onStderr?: (data: string) => void;
// 		// terminal?: vscode.Terminal;
// 	} = {}
// ): Promise<number> {
// 	return new Promise((resolve, reject) => {
// 		const proc = spawn(command, args, {
// 			cwd: options.cwd,
// 			shell: true,
// 		});

// 		proc.stdout.on('data', (data) => {
// 			const text = data.toString();
// 			options.onStdout?.(text);

// 			// if (options.terminal) {
// 			//   options.terminal.sendText(text, false);
// 			// }
// 		});

// 		proc.stderr.on('data', (data) => {
// 			const text = data.toString();
// 			options.onStderr?.(text);

// 			// if (options.terminal) {
// 			//   options.terminal.sendText(text, false);
// 			// }
// 		});

// 		proc.on('close', (code) => {
// 			resolve(code ?? 0);
// 		});

// 		proc.on('error', (err) => {
// 			reject(err);
// 		});
// 	});
// }
// const devDeps = [
// 	'@eslint/compat',
// 	'@eslint/js',
// 	'@prisma/config',
// 	'@types/pg',
// 	'@types/eslint',
// 	'@sveltejs/vite-plugin-svelte',
// 	'@tsconfig/svelte',
// 	'tslib',
// 	'@types/bcrypt',
// 	'@types/node',
// 	'@typescript-eslint/eslint-plugin',
// 	'@typescript-eslint/parser',
// 	'eslint',
// 	'eslint-config-prettier',
// 	'eslint-plugin-svelte',
// 	'globals',
// 	'postcss',
// 	'postcss-load-config',
// 	'prettier',
// 	'prettier-plugin-svelte',
// 	'prisma',
// 	'sass',
// 	'sass-embedded',
// 	'svelte',
// 	'svelte-check',
// 	'svelte-preprocess',
// 	'ts-node',
// 	'typescript',
// 	'typescript-eslint',
// 	'vite',
// 	'vite-plugin-sass-dts',
// ];
// const deps = ['@prisma/adapter-pg', '@prisma/client', '@prisma/internals', 'bcrypt', 'dotenv', 'pg', 'tslib'];
// const init = ['prisma', 'init', '--datasource-provider', 'postgresql'];
// The function should be named `load` and exported.
// The type `PageServerLoad` is generated by SvelteKit's type system ($types).
export const load: PageServerLoad = async () => {
	// await runCommandStream('pnpm', ['i', '-D', ...devDeps], {
	// 	cwd: paths.root,
	// 	onStdout: (msg) => console.log(msg),
	// 	onStderr: (err) => console.error(err),
	// });
	// await runCommandStream('pnpm', ['i', '-D', ...deps], {
	// 	cwd: paths.root,
	// 	onStdout: (msg) => console.log(msg),
	// 	onStderr: (err) => console.error(err),
	// });
	// await runCommandStream('pnpm dlx', [...init], {
	// 	cwd: paths.root,
	// 	onStdout: (msg) => console.log(msg),
	// 	onStderr: (err) => console.error(err),
	// });
	// console.log((await execShell('whoami')).trim());

	const schema = fs.readFileSync(path.join(process.cwd(), 'prisma', 'schema.prisma'), 'utf-8');
	const models = parsePrismaSchema(schema);
	console.log('server models begin', JSON.stringify(models, null, 2), '\nserver models end');
	// Return the data as an object
	// const strModels = JSON.stringify({ uiModels, nuiModels, fieldStrips });
	return models;
};
